version: "2"
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "app/models/user.rb"

method-count:
    config:
      threshold: 25

engines:
  duplication:
    enabled: true
    exclude_paths:
      - "app/avo/actions/**/*"
      - "app/avo/fields/**/*"
      - "app/avo/resources/**/*"
