inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test

Metrics/AbcSize:
  Max: 42 # TODO: Lower to 15

Metrics/ClassLength:
  Max: 350 # TODO: Lower to 100
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30 # TODO: Lower to 10

Metrics/ModuleLength:
  Exclude:
    - lib/patterns.rb
    - app/models/concerns/rubygem_searchable.rb

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

Performance/RedundantMerge:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AndOr:
  Exclude:
    - app/controllers/internal/ping_controller.rb

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/application_controller.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false

Style/SafeNavigation:
  Enabled: true
