inherit_from: .rubocop_todo.yml
require:
  - ./test/safe_navigation_cop.rb
  - rubocop-performance

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - app/helpers/dynamic_errors_helper.rb
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# TODO: Enable on rubocop 0.67.3
Rails/ActiveRecordOverride:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test

Layout/AlignArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 42 # TODO: Lower to 15

Metrics/ClassLength:
  Max: 350 # TODO: Lower to 100
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30 # TODO: Lower to 10

Metrics/ModuleLength:
  Exclude:
    - lib/patterns.rb
    - app/models/concerns/rubygem_searchable.rb

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

# TODO: Enable on rubocop 0.67.3
Naming/RescuedExceptionsVariableName:
  Exclude:
    - app/jobs/notifier.rb

Performance/RedundantMerge:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AndOr:
  Exclude:
    - app/controllers/internal/ping_controller.rb

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/application_controller.rb

Style/CustomSafeNavigationCop:
  Exclude:
    - app/models/links.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false
