services:
  db:
    image: index.docker.io/library/postgres@sha256:2a453914efff6156786247b2399e6f9f18d7fc37e1ca5574a23aba172cf37d3e # 14.15
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres", "--host", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 12
  cache:
    image: index.docker.io/library/memcached@sha256:f4504742a8fb03c3ac0cd172e1c1d2277117629f8d21d52f78307121ddc3de5f # 1.4.39
    ports:
      - "127.0.0.1:11211:11211"
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "exec 3<>/dev/tcp/127.0.0.1/11211 && printf 'version\\r\\n' >&3 && head -c 7 <&3 | grep -q VERSION",
        ]
      interval: 5s
      timeout: 5s
      retries: 12
  search:
    image: index.docker.io/opensearchproject/opensearch@sha256:2e954ff0e8c9d0f4868b4818150b3aecc92fbb0cc4a24d00dace38ada227291d # 2.13.0
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "127.0.0.1:9200:9200"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--silent",
          "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=5s",
        ]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 60s
  search-console:
    image: index.docker.io/opensearchproject/opensearch-dashboards@sha256:d8f4442da4d0cb44865a5eab01c9eb9f00769e2d5f053d21e3ff3c64a50fc6ec # 2.13.0
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:5601/api/status || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 120s
    depends_on:
      search:
        condition: service_healthy
