#!/usr/bin/env ruby

require_relative '../../config/boot'
require_relative '../../config/environment'

require 'tuf/gemcutter'

private_file = ARGV.shift
public_file  = ARGV.shift
indir        = ARGV.shift

# TODO: DRY this up with Indexer
def fog
  $fog || Fog::Storage.new(
    :provider   => 'Local',
    :local_root => Pusher.server_path
  )
end

bucket = PublicFileBucket.new(
  fog.directories.get($rubygems_config[:s3_bucket]) ||
  fog.directories.create(key: $rubygems_config[:s3_bucket])
)
key = Tuf::Key.build('rsa', File.read(private_file), File.read(public_file))

signed_files = {
  'root'            => JSON.parse(File.read(indir + '/root.txt')),
  'targets'         => JSON.parse(File.read(indir + '/targets.txt')),
  'targets/claimed' => JSON.parse(File.read(indir + '/claimed.txt'))
}

Tuf::Gemcutter.new.bootstrap!(bucket, key, signed_files)
