name: "Setup rubygems.org"
description: "Setup steps for rubygems.org"
inputs:
  ruby-version:
    description: "Ruby version to use"
    required: true
  rubygems-version:
    description: "RubyGems version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install and start services
      shell: bash
      run: |
        docker-compose up -d
    - name: Wait for ES to boot
      shell: bash
      run: |
        timeout 300 bash -c "until curl --silent --output /dev/null http://localhost:9200/_cat/health?h=st; do printf '.'; sleep 5; done; printf '\n'"
    - uses: ruby/setup-ruby@a05e47355e80e57b9a67566a813648fa67d92011 # v1.157.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
    - name: set rubygems version
      shell: bash
      run: |
        if [ "${{ inputs.rubygems-version }}" != "latest" ]; then
          gem update --system ${{ inputs.rubygems-version }};
        else
          gem update --system
        fi
        gem --version
        bundle --version
    - name: Prepare environment
      shell: bash
      run: |
        cp config/database.yml.sample config/database.yml
        bundle exec rake db:setup assets:precompile
