name: "Setup rubygems.org"
description: "Setup steps for rubygems.org"
inputs:
  ruby-version:
    description: "Ruby version to use"
    required: true
  rubygems-version:
    description: "RubyGems version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install and start services
      shell: bash
      run: |
        docker-compose up -d
    - name: Wait for ES to boot
      shell: bash
      run: |
        timeout 300 bash -c "until curl --silent --output /dev/null http://localhost:9200/_cat/health?h=st; do printf '.'; sleep 5; done; printf '\n'"
    - uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        rubygems: ${{ inputs.rubygems-version }}
    - name: Print bundle environment
      shell: bash
      run: bundle env
    - name: Prepare environment
      shell: bash
      run: |
        cp config/database.yml.sample config/database.yml
        bundle exec rake db:setup assets:precompile
