name: "Setup rubygems.org"
description: "Setup steps for rubygems.org"
inputs:
  ruby-version:
    description: "Ruby version to use"
    required: true
  rubygems-version:
    description: "RubyGems version to use"
    required: true
  install-avo-pro:
    description: "Install Avo gem"
    required: false
    default: "true"
  install-playwright:
    description: "Install Playwright browsers (only needed for system tests)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install and start services
      shell: bash
      run: |
        docker compose up -d --wait
    - name: Configure bundler environment
      shell: bash
      if: inputs.install-avo-pro == 'true'
      run: |
        printf "BUNDLE_WITH=avo\nRAILS_GROUPS=avo\n" >> $GITHUB_ENV
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        rubygems: ${{ inputs.rubygems-version }}
    - name: Print bundle environment
      shell: bash
      run: bundle env
    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true'
      shell: bash
      run: bin/playwright install --with-deps chromium
    - name: Prepare environment
      shell: bash
      run: |
        cp config/database.yml.sample config/database.yml
        bundle exec rake db:setup assets:precompile
