# syntax = docker/dockerfile:1.4

ARG RUBY_VERSION=3.3.5
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION

RUN sudo apt-get update && sudo apt-get -y install --no-install-recommends pkg-config
