services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - search
      - db
      - selenium

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
