# frozen_string_literal: true

require "test_helper"

class Maintenance::BackfillUserWebauthnIdsTaskTest < ActiveSupport::TestCase
  test "#process sets a WebAuthn ID" do
    user = create(:user)
    user.update_column(:webauthn_id, nil)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert user.reload.webauthn_id
  end

  test "#process handles an ID generated by the old initialization callback" do
    user = create(:user)
    user.update_column(:webauthn_id, nil)
    user.webauthn_id = WebAuthn.generate_user_id

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert user.reload.webauthn_id
  end

  test "#process does not overwrite an ID set after the user was loaded" do
    user = create(:user)
    user.update_column(:webauthn_id, nil)
    stale_user = User.find(user.id)
    current_id = WebAuthn.generate_user_id
    user.update_column(:webauthn_id, current_id)

    Maintenance::BackfillUserWebauthnIdsTask.process(stale_user)

    assert_equal current_id, user.reload.webauthn_id
  end

  test "#process skips a user deleted after being loaded" do
    user = create(:user)
    user.update_column(:webauthn_id, nil)
    user.update_column(:deleted_at, Time.current)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert_nil user.reload.webauthn_id_in_database
  end

  test "#process skips a user with WebAuthn credentials" do
    user = create(:user)
    user.update_column(:webauthn_id, nil)
    create(:webauthn_credential, user:)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert_nil user.reload.webauthn_id_in_database
  end

  test "#count returns active users without a WebAuthn ID or credentials" do
    missing_id = create(:user)
    missing_id.update_column(:webauthn_id, nil)
    create(:user)
    deleted = create(:user)
    deleted.update_columns(deleted_at: Time.current, webauthn_id: nil)
    credential_user = create(:user)
    credential_user.update_column(:webauthn_id, nil)
    create(:webauthn_credential, user: credential_user)

    assert_equal 1, Maintenance::BackfillUserWebauthnIdsTask.count
  end
end
