# frozen_string_literal: true

require "test_helper"

class Maintenance::BackfillUserWebauthnIdsTaskTest < ActiveSupport::TestCase
  setup do
    @task = Maintenance::BackfillUserWebauthnIdsTask.new
  end

  test "#process sets a WebAuthn ID" do
    user = create(:user, :without_webauthn_id)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert user.reload.webauthn_id_in_database
  end

  test "#process handles an ID generated by the old initialization callback" do
    user = create(:user, :without_webauthn_id)
    user.webauthn_id = WebAuthn.generate_user_id

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert user.reload.webauthn_id_in_database
  end

  test "#process does not overwrite an ID set after the user was loaded" do
    user = create(:user, :without_webauthn_id)
    stale_user = User.find(user.id)
    current_id = WebAuthn.generate_user_id
    user.update_column(:webauthn_id, current_id)

    Maintenance::BackfillUserWebauthnIdsTask.process(stale_user)

    assert_equal current_id, user.reload.webauthn_id
  end

  test "#process skips a user deleted after being loaded" do
    user = create(:user, :without_webauthn_id)
    user.update_column(:deleted_at, Time.current)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert_nil user.reload.webauthn_id_in_database
  end

  test "#process skips a user with WebAuthn credentials" do
    user = create(:user, :without_webauthn_id)
    create(:webauthn_credential, user:)

    Maintenance::BackfillUserWebauthnIdsTask.process(user)

    assert_nil user.reload.webauthn_id_in_database
  end

  test "#collection includes only active users without a WebAuthn ID or credentials" do
    missing_id = create(:user, :without_webauthn_id)
    create(:user)
    deleted = create(:user, :without_webauthn_id)
    deleted.update_column(:deleted_at, Time.current)
    credential_user = create(:user, :without_webauthn_id)
    create(:webauthn_credential, user: credential_user)

    assert_equal [missing_id.id], @task.collection.ids
  end

  test "#collection applies min_user_id as an inclusive lower bound" do
    users = create_list(:user, 3, :without_webauthn_id)
    @task.min_user_id = users.second.id

    assert_equal users.drop(1).map(&:id), @task.collection.order(:id).ids
  end

  test "#collection applies max_user_id as an inclusive upper bound" do
    users = create_list(:user, 3, :without_webauthn_id)
    @task.max_user_id = users.second.id

    assert_equal users.first(2).map(&:id), @task.collection.order(:id).ids
  end

  test "is invalid when max_user_id is below min_user_id" do
    @task.min_user_id = 10
    @task.max_user_id = 5

    refute_predicate @task, :valid?
    assert_includes @task.errors[:max_user_id], "must be greater than or equal to min_user_id"
  end
end
