#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'production'
require_relative '../config/environment'

Version.find_in_batches do |versions|
  versions.each do |version|
    print "sizing #{version.full_name}: "
    file = RubygemFs.instance.get("gems/#{version.full_name}.gem")
    if file
      begin
        size = file.bytesize
        version.update_attribute(:size, size)
        print "succeeded (#{size})\n"
      rescue => e
        print "failed - #{e.message}"
      end
    else
      print "failed - file not found"
    end
  end
end
