#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'production'
require_relative '../config/environment'
require 'fog'

def fog
  $fog || Fog::Storage.new(:provider => 'Local',
                           :local_root => Pusher.server_path('gems'))
end

Version.find_in_batches do |versions|
  versions.each do |version|
    print "sizing #{version.full_name}: "
    file = fog.directories.get(Gemcutter.config['s3_bucket'] + '/gems') \
      .files.get("#{version.full_name}.gem")
    if file
      begin
        size = file.content_length.bytes
        version.update_attribute(:size, size)
        print "succeeded (#{size})\n"
      rescue => e
        print "failed - #{e.message}"
      end
    else
      print "failed - file not found"
    end
  end
end
