#!/usr/bin/env ruby

if ARGV.empty?
  puts "Locks a user account so it can't be used."
  puts "USAGE: script/block_user USERNAME"
  exit
end

handle = ARGV.first
puts "Locking user #{handle}..."

ENV["RAILS_ENV"] ||= "production"
require_relative "../config/environment"

begin
  User.find_by!(handle: handle).block!
  puts "Done."
rescue ActiveRecord::RecordNotFound
  puts "User #{handle} not found."
  exit 1 # return non-zero on fail
end
