#!/usr/bin/env ruby

if ARGV.empty?
  puts "Locks a user account so it can't be used."
  puts "USAGE: script/malicious_user USERNAME"
  exit
end

handle = ARGV.first
puts "Locking user #{handle}..."

ENV["RAILS_ENV"] ||= "production"
require_relative "../config/environment"

user = User.where(handle: handle).first

user.update_attribute(:email, "security+locked-#{handle}@rubygems.org")
user.disable_mfa!
user.update!(
  password: SecureRandom.alphanumeric,
  remember_token: nil,
  remember_token_expires_at: nil,
  api_key: nil
)

puts "Done."
