#!/usr/bin/env ruby

if ARGV.empty?
  puts "Yanks all gems belonging to a user and prevents future logins."
  puts "USAGE: script/malicious_user USERNAME"
  exit
end

handle = ARGV.first
puts "Suspending malicious user #{handle}..."

ENV["RAILS_ENV"] ||= "production"
require_relative "../config/environment"

user = User.where(handle: handle).first

puts "Locking account... "
user.update_attribute(email: "security+locked-#{handle}@rubygems.org")
user.disable_mfa!
user.update!(
  password: SecureRandom.alphanumeric,
  remember_token: nil,
  remember_token_expires_at: nil,
  api_key: nil
)

user.rubygems.each do |rubygem|
  puts "Yanking #{rubygem.name}"
  rubygem.versions.each do |version|
    puts "  #{version}"
    user.deletions.create!(version: version) unless version.yanked?
  end
end

puts "Done."
