#!/usr/bin/env ruby

unless ARGV.size == 2
  abort "Usage: script/permadelete_version [GEM_NAME] [VERSION]"
end

ENV['RAILS_ENV'] ||= 'production'
require_relative '../config/environment'

name, version = ARGV
rubygem = Rubygem.find_by_name!(name)
version = rubygem.versions.find_by_number!(version)
full_name = version.full_name

require 'highline'
terminal = HighLine.new
confirm  = terminal.ask("Are you sure you want to permadelete #{full_name}? (Y/N)")

if confirm.upcase == "Y" || confirm.upcase == "YES"
  owner = rubygem.owners.first
  owner.deletions.create!(version: version)

  puts "#{full_name} permadeleted."
else
  abort "No problem! #{full_name} lives on."
end
