#!/usr/bin/env ruby

unless name = ARGV.first
  abort "Usage: script/permadelete [GEM_NAME]"
end

ENV['RAILS_ENV'] ||= 'production'
require_relative '../config/environment'

rubygem = Rubygem.find_by_name!(name)

if !rubygem
  puts "Gem '#{name}' was not found!"
  exit 1
end

names   = rubygem.versions.map(&:full_name)

require 'highline'
terminal = HighLine.new
confirm  = terminal.ask("Are you sure you want to permadelete #{name} with #{names.size} versions? (Y/N)")

if confirm.upcase == "Y" || confirm.upcase == "YES"
  names.each do |n|
    RubygemFs.instance.remove("gems/#{n}.gem")
    RubygemFs.instance.remove("quick/Marshal.4.8/#{n}.gemspec.rz")
  end

  rubygem.destroy

  puts "#{name} permadeleted."
else
  abort "No problem! #{name} lives on."
end
