#!/bin/sh
set -e
export PATH="$(dirname "$0")/../bin:$PATH"  # Use binstubs

if [ "$1" = "-v" ]; then
  exec 3>&1
else
  exec 3>/dev/null
fi

if [ ! -f config/database.yml ]; then
  echo "$0: Copying database.yml.sample over"
  cp config/database.yml.sample config/database.yml
fi

# Wipe out logs and scss cache.
echo "$0: Cleaning out old logs"
{ rm -f log/*
} >&3 2>&1

# Install dependencies
echo "$0: Installing libraries and plugins"
{ gem list -i bundler || gem install bundler
  bundle
  script/install_toxiproxy.sh
} >&3 2>&1

# Wipe and load the database unless KEEPDB=1 env var is set.
if [ -z "$KEEPDB" ]; then
  echo "$0: Reloading the database"
  { rake db:create:all db:drop:all db:setup --trace
    rake db:test:prepare --trace
  } >&3 2>&1
fi

echo "$0: Restarting Pow/Passenger"
mkdir -p tmp
touch tmp/restart.txt

echo "$0: Done!"
